local mime_tbl = {
	['.rss'] = 'application/rss+xml',
	['.7z'] = 'application/x-7z-compressed',
	['.mml'] = 'text/mathml',
	['.tcl'] = 'application/x-tcl',
	['.tk'] = 'application/x-tcl',
	['.jad'] = 'text/vnd.sun.j2me.app-descriptor',
	['.der'] = 'application/x-x509-ca-cert',
	['.pem'] = 'application/x-x509-ca-cert',
	['.crt'] = 'application/x-x509-ca-cert',
	['.wml'] = 'text/vnd.wap.wml',
	['.xpi'] = 'application/x-xpinstall',
	['.htc'] = 'text/x-component',
	['.xhtml'] = 'application/xhtml+xml',
	['.png'] = 'image/png',
	['.xspf'] = 'application/xspf+xml',
	['.tif'] = 'image/tiff',
	['.tiff'] = 'image/tiff',
	['.pptx'] = 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
	['.wbmp'] = 'image/vnd.wap.wbmp',
	['.run'] = 'application/x-makeself',
	['.mid'] = 'audio/midi',
	['.ico'] = 'image/x-icon',
	['.kar'] = 'audio/midi',
	['.dmg'] = 'application/octet-stream',
	['.woff'] = 'application/font-woff',
	['.mp3'] = 'audio/mpeg',
	['.iso'] = 'application/octet-stream',
	['.img'] = 'application/octet-stream',
	['.jar'] = 'application/java-archive',
	['.war'] = 'application/java-archive',
	['.ear'] = 'application/java-archive',
	['.html'] = 'text/html',
	['.htm'] = 'text/html',
	['.shtml'] = 'text/html',
	['.eps'] = 'application/postscript',
	['.ai'] = 'application/postscript',
	['.docx'] = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
	['.webp'] = 'image/webp',
	['.hqx'] = 'application/mac-binhex40',
	['.rtf'] = 'application/rtf',
	['.xlsx'] = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
	['.3gpp'] = 'video/3gpp',
	['.doc'] = 'application/msword',
	['.m3u8'] = 'application/vnd.apple.mpegurl',
	['.pdf'] = 'application/pdf',
	['.xls'] = 'application/vnd.ms-excel',
	['.ps'] = 'application/postscript',
	['.eot'] = 'application/vnd.ms-fontobject',
	['.mpeg'] = 'video/mpeg',
	['.ppt'] = 'application/vnd.ms-powerpoint',
	['.zip'] = 'application/zip',
	['.dll'] = 'application/octet-stream',
	['.wmlc'] = 'application/vnd.wap.wmlc',
	['.msp'] = 'application/octet-stream',
	['.msm'] = 'application/octet-stream',
	['.m4a'] = 'audio/x-m4a',
	['.kml'] = 'application/vnd.google-earth.kml+xml',
	['.ts'] = 'video/mp2t',
	['.flv'] = 'video/x-flv',
	['.webm'] = 'video/webm',
	['.kmz'] = 'application/vnd.google-earth.kmz',
	['.mov'] = 'video/quicktime',
	['.mpg'] = 'video/mpeg',
	['.mp4'] = 'video/mp4',
	['.m4v'] = 'video/x-m4v',
	['.3gp'] = 'video/3gpp',
	['.ra'] = 'audio/x-realaudio',
	['.cco'] = 'application/x-cocoa',
	['.mng'] = 'video/x-mng',
	['.ogg'] = 'audio/ogg',
	['.midi'] = 'audio/midi',
	['.jardiff'] = 'application/x-java-archive-diff',
	['.asx'] = 'video/x-ms-asf',
	['.asf'] = 'video/x-ms-asf',
	['.msi'] = 'application/octet-stream',
	['.jnlp'] = 'application/x-java-jnlp-file',
	['.deb'] = 'application/octet-stream',
	['.wmv'] = 'video/x-ms-wmv',
	['.exe'] = 'application/octet-stream',
	['.css'] = 'text/css',
	['.bin'] = 'application/octet-stream',
	['.avi'] = 'video/x-msvideo',
	['.pl'] = 'application/x-perl',
	['.pm'] = 'application/x-perl',
	['.jng'] = 'image/x-jng',
	['.bmp'] = 'image/x-ms-bmp',
	['.atom'] = 'application/atom+xml',
	['.prc'] = 'application/x-pilot',
	['.pdb'] = 'application/x-pilot',
	['.js'] = 'application/javascript',
	['.svgz'] = 'image/svg+xml',
	['.jpeg'] = 'image/jpeg',
	['.rar'] = 'application/x-rar-compressed',
	['.gif'] = 'image/gif',
	['.jpg'] = 'image/jpeg',
	['.json'] = 'application/json',
	['.rpm'] = 'application/x-redhat-package-manager',
	['.svg'] = 'image/svg+xml',
	['.xml'] = 'text/xml',
	['.swf'] = 'application/x-shockwave-flash',
	['.sea'] = 'application/x-sea',
	['.sit'] = 'application/x-stuffit',
	['.txt'] = 'text/plain',
}
local len_tbl = {
	3,
	4,
	5,
	6,
	8,
}
local function getPathMIME(path)
    if not path or path:len() <= 0 then
        return
    end
    local plen = path:len()
    for _, klen in ipairs(len_tbl) do
        if plen <= klen then
            break
        end
        local fsuffix = path:sub(plen - klen + 1):lower()
        local mime = mime_tbl[fsuffix]
        if mime then
            return fsuffix, mime
        end
    end
end
return {
	getPathMIME = getPathMIME
}
